[package]
name = "studybible"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.7.0-rc.0", features = ["desktop"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["full"] }

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
